-- Universal Banking Birthday Wishes Notification API
-- Snowflake migration for the existing MYDATABASE.PUBLIC.BANK_CUSTOMER_DATA table.
-- Run once before deploying/restarting the Mule application.

ALTER TABLE MYDATABASE.PUBLIC.BANK_CUSTOMER_DATA
    ADD COLUMN IF NOT EXISTS STATUS VARCHAR DEFAULT 'ACTIVE';

ALTER TABLE MYDATABASE.PUBLIC.BANK_CUSTOMER_DATA
    ADD COLUMN IF NOT EXISTS BIRTHDAY_WISH_SENT BOOLEAN DEFAULT FALSE;

ALTER TABLE MYDATABASE.PUBLIC.BANK_CUSTOMER_DATA
    ADD COLUMN IF NOT EXISTS BIRTHDAY_WISH_SENT_DATE TIMESTAMP_NTZ;

-- Normalize existing rows so the API can safely use the new columns.
UPDATE MYDATABASE.PUBLIC.BANK_CUSTOMER_DATA
SET
    STATUS = COALESCE(STATUS, 'ACTIVE'),
    BIRTHDAY_WISH_SENT = COALESCE(BIRTHDAY_WISH_SENT, FALSE)
WHERE STATUS IS NULL
   OR BIRTHDAY_WISH_SENT IS NULL;

-- Verify the migration.
DESC TABLE MYDATABASE.PUBLIC.BANK_CUSTOMER_DATA;
