-- Shared cross-region notification outbox. Run once before deploying the worker.
CREATE TABLE IF NOT EXISTS MYDATABASE.PUBLIC.BANK_NOTIFICATION_OUTBOX (
 NOTIFICATION_ID VARCHAR(200) NOT NULL,
 CUSTOMER_ID VARCHAR(200) NOT NULL,
 NOTIFICATION_TYPE VARCHAR(50) NOT NULL,
 BUSINESS_DATE DATE NOT NULL,
 FULLNAME VARCHAR(500), EMAIL VARCHAR(500), BANKNAME VARCHAR(500), MOBILENUMBER VARCHAR(100),
 STATUS VARCHAR(30) NOT NULL DEFAULT 'PENDING',
 OWNER VARCHAR(200), LEASE_UNTIL TIMESTAMP_NTZ,
 ATTEMPT_COUNT NUMBER(10,0) NOT NULL DEFAULT 0,
 NEXT_ATTEMPT_AT TIMESTAMP_NTZ, PROVIDER_MESSAGE_ID VARCHAR(500), SENT_AT TIMESTAMP_NTZ,
 LAST_ERROR VARCHAR(5000),
 CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
 UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);
-- Standard-table constraints are informational in Snowflake. The app enforces idempotency with MERGE
-- and ownership with conditional UPDATE. Snowflake DML statements acquire locks while modifying resources.
